### ISSUE TITLE
Remover endpoints que ofrecen datos sobre pacientes recuperados

### ISSUE THREAD

**Issue by sanguineti** [sanguineti/chile-coronapi#31]
Debido a lo irregular que son los datos de "confirmados" que entrega el gobierno (literalmente es la resta entre la cantidad de contagiados hace 14 días y la cantidad de muertos) en [covid19-data](https://github.com/jorgeperezrojas/covid19-data) se han removido dichos datos. Con motivo de esto es que los endpoints que usan esa info han dejado de funcionar.

Se debe remover ese acceso para que la API vuelva a funcionar.

**Comment by cmesiasd** [comment]
Solucionado en #33 😁
