### ISSUE TITLE
Problema con los datos a contar del 29 de abril.

### ISSUE THREAD

**Issue by sanguineti** [sanguineti/chile-coronapi#32]
De momento no se entregan datos desde el 29 de abril, debido a cambios que el MINSAL y el gobierno han hecho en cómo presentan la información en su sitio, además de cómo están contando a los contagiados.

Esperamos disponibilizar esta información a través de la API tan pronto como se tengan más claridades sobre los datos confusos que se están entregando.

**Comment by cmesiasd** [comment]
Problema solucionado en el repo de [covid19-data](https://github.com/jorgeperezrojas/covid19-data)
