### ISSUE TITLE
GET historical/communes debería responder un formato consistente con historical/regions

### ISSUE THREAD

**Issue by maugsbur** [sanguineti/chile-coronapi#50]
Comportamiento esperado: GET historical/communes debería entregar objetos con un atributo _communeData_ con el siguiente formato:
`communeData: {
03/07/2020: {
confirmed: 10
},
03/08/2020: {
confirmed: 15
},
...}`
De esta manera se puede usar de forma consistente con GET historical/nation y GET historical/regions, y se puede extender con el mismo formato a medida que se agregan más datos a nivel comunal (muertes, etc.).

Comportamiento actual: GET historical/communes entrega objetos con un atributo _confirmed_ con el siguiente formato:
`confirmed: {
03/30/2020: 5,
04/01/2020: 9,
...}`

Discusión: Cómo afecta esto a los proyectos existentes? Esto implicaría tener una API v4?

**Comment by cmesiasd** [comment]
Hola! 
Gracias por reportar esto. Efectivamente hay una inconsistencia en el formato de historical/communes. Pero cambiarlo en v3 podría afectar a los proyectos existentes. 
Ahora bien, ya estamos trabajando en la API v4, por lo que ahí podemos solucionarlo, sin afectar a otros. 
Saludos 😁

**Comment by sanguineti** [comment]
Hola!
Muy en la línea de lo que comenta @cmesiasd, muy pronto liberaremos cambios respecto de cómo se muestran las comunas. Se seguirá dando soporte a los proyectos que usan la versión antigua, por lo que este endpoint se organizará usando v4.
Saludos!

**Comment by sanguineti** [comment]
Actualizado

**Comment by maugsbur** [comment]
Excelente! Muchas gracias!
