### ISSUE TITLE
Agregar recuperados

### ISSUE THREAD

**Issue by sergioazoc** [sanguineti/chile-coronapi#53]
Hola, en la documentación aparece que van incluidos los datos de los recuperados, pero no los está entregando en realidad.

**Comment by cmesiasd** [comment]
Hola estimado, 

Como dice en la documentación (ver README.md sección IMPORTANTE) no entregamos, ni entregaremos el dato sobre pacientes recuperados, dado que carecen de validez científica.

Saludos!

**Comment by sanguineti** [comment]
Hola @sergioazoc, efectivamente es como comenta @cmesiasd. Se nos olvidó borrarlo en su momento de la documentación de dos endpoints, lo haremos ASAP.
Saludos!

**Comment by sanguineti** [comment]
Listo!
