### ISSUE TITLE
Http error 500 en algunos endpoints

### ISSUE THREAD

**Issue by jtatria** [sanguineti/chile-coronapi#56]
Varios endpoints en v4 estan tirando http error 500 al menos desde hoy.

````
$ curl https://chile-coronapi.herokuapp.com/api/v4/historical/communes
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
````
En conversacion con Franco me indicó que al parecer sería debido a un error en el formato de origen de los datos, que contiene decimales para los valores de la última semana, lo que hace explotar el parser de datos.

**Comment by sanguineti** [comment]
Gracias por el aviso. El problema se solucionó finalmente en la fuente de los datos el mismo día que se notificó.
